import User from './User/User.js'
import { HeaderModel } from '../domain/HeaderModel.js'
import { FooterModel } from '../domain/FooterModel.js'
import { HeroModel } from '../domain/HeroModel.js'
import {
	ButtonModel,
	ConfirmModel,
	InputModel,
	SpinnerModel,
	TableModel,
	ToastModel,
	SelectModel,
	AutocompleteModel,
	TreeModel,
	TabsModel,
	AccordionModel,
	GalleryModel,
	PriceModel,
	PricingModel,
	CommentModel,
	TestimonialModel,
	StatsItemModel,
	StatsModel,
	TimelineItemModel,
	TimelineModel,
	EmptyStateModel,
	BannerModel,
	ProfileDropdownModel,
} from '../domain/components/index.js'

export {
	User,
	HeaderModel,
	FooterModel,
	HeroModel,
	ButtonModel,
	ConfirmModel,
	InputModel,
	SpinnerModel,
	TableModel,
	ToastModel,
	SelectModel,
	AutocompleteModel,
	TreeModel,
	TabsModel,
	AccordionModel,
	GalleryModel,
	PriceModel,
	PricingModel,
	CommentModel,
	TestimonialModel,
	StatsItemModel,
	StatsModel,
	TimelineItemModel,
	TimelineModel,
	EmptyStateModel,
	BannerModel,
	ProfileDropdownModel,
}

const Models = {
	User,
	HeaderModel,
	FooterModel,
	HeroModel,
	ButtonModel,
	ConfirmModel,
	InputModel,
	SpinnerModel,
	TableModel,
	ToastModel,
	SelectModel,
	AutocompleteModel,
	TreeModel,
	TabsModel,
	AccordionModel,
	GalleryModel,
	PriceModel,
	PricingModel,
	CommentModel,
	TestimonialModel,
	StatsItemModel,
	StatsModel,
	TimelineItemModel,
	TimelineModel,
	EmptyStateModel,
	BannerModel,
	ProfileDropdownModel,
}

export default Models
