export default Model;
import User from './User/User.js';
import { HeaderModel } from '../domain/HeaderModel.js';
import { FooterModel } from '../domain/FooterModel.js';
import { HeroModel } from '../domain/HeroModel.js';
import { ButtonModel } from '../domain/components/index.js';
import { ConfirmModel } from '../domain/components/index.js';
import { InputModel } from '../domain/components/index.js';
import { SpinnerModel } from '../domain/components/index.js';
import { TableModel } from '../domain/components/index.js';
import { ToastModel } from '../domain/components/index.js';
import { SelectModel } from '../domain/components/index.js';
import { AutocompleteModel } from '../domain/components/index.js';
import { TreeModel } from '../domain/components/index.js';
import { TabsModel } from '../domain/components/index.js';
import { AccordionModel } from '../domain/components/index.js';
import { GalleryModel } from '../domain/components/index.js';
import { PriceModel } from '../domain/components/index.js';
import { PricingModel } from '../domain/components/index.js';
import { CommentModel } from '../domain/components/index.js';
import { TestimonialModel } from '../domain/components/index.js';
import { StatsItemModel } from '../domain/components/index.js';
import { StatsModel } from '../domain/components/index.js';
import { TimelineItemModel } from '../domain/components/index.js';
import { TimelineModel } from '../domain/components/index.js';
import { EmptyStateModel } from '../domain/components/index.js';
import { BannerModel } from '../domain/components/index.js';
import { ProfileDropdownModel } from '../domain/components/index.js';
declare namespace Model {
    export { User };
    export { HeaderModel };
    export { FooterModel };
    export { HeroModel };
    export { ButtonModel };
    export { ConfirmModel };
    export { InputModel };
    export { SpinnerModel };
    export { TableModel };
    export { ToastModel };
    export { SelectModel };
    export { AutocompleteModel };
    export { TreeModel };
    export { TabsModel };
    export { AccordionModel };
    export { GalleryModel };
    export { PriceModel };
    export { PricingModel };
    export { CommentModel };
    export { TestimonialModel };
    export { StatsItemModel };
    export { StatsModel };
    export { TimelineItemModel };
    export { TimelineModel };
    export { EmptyStateModel };
    export { BannerModel };
    export { ProfileDropdownModel };
}
export { User, HeaderModel, FooterModel, HeroModel, ButtonModel, ConfirmModel, InputModel, SpinnerModel, TableModel, ToastModel, SelectModel, AutocompleteModel, TreeModel, TabsModel, AccordionModel, GalleryModel, PriceModel, PricingModel, CommentModel, TestimonialModel, StatsItemModel, StatsModel, TimelineItemModel, TimelineModel, EmptyStateModel, BannerModel, ProfileDropdownModel };
