export { User };
export const HeaderModel: typeof DomainModels.HeaderModel;
export const FooterModel: typeof DomainModels.FooterModel;
export const HeroModel: typeof DomainModels.HeroModel;
export const ButtonModel: typeof DomainModels.ButtonModel;
export const ConfirmModel: typeof DomainModels.ConfirmModel;
export const InputModel: typeof DomainModels.InputModel;
export const SpinnerModel: typeof DomainModels.SpinnerModel;
export const TableModel: typeof DomainModels.TableModel;
export const ToastModel: typeof DomainModels.ToastModel;
export const SelectModel: typeof DomainModels.SelectModel;
export const AutocompleteModel: typeof DomainModels.AutocompleteModel;
export const TreeModel: typeof DomainModels.TreeModel;
export const TabsModel: typeof DomainModels.TabsModel;
export const AccordionModel: typeof DomainModels.AccordionModel;
export const GalleryModel: typeof DomainModels.GalleryModel;
export const PriceModel: typeof DomainModels.PriceModel;
export const PricingModel: typeof DomainModels.PricingModel;
export const CommentModel: typeof DomainModels.CommentModel;
export const TestimonialModel: typeof DomainModels.TestimonialModel;
export const StatsItemModel: typeof DomainModels.StatsItemModel;
export const StatsModel: typeof DomainModels.StatsModel;
export const TimelineItemModel: typeof DomainModels.TimelineItemModel;
export const TimelineModel: typeof DomainModels.TimelineModel;
export default Model;
import User from './User/User.js';
import * as DomainModels from '../domain/index.js';
declare const Model: {
    SandboxModel: typeof DomainModels.SandboxModel;
    ShowcaseAppModel: typeof DomainModels.ShowcaseAppModel;
    Navigation: typeof DomainModels.Navigation;
    Language: any;
    HeaderModel: typeof DomainModels.HeaderModel;
    FooterModel: typeof DomainModels.FooterModel;
    HeroModel: typeof DomainModels.HeroModel;
    ButtonModel: typeof DomainModels.ButtonModel;
    ConfirmModel: typeof DomainModels.ConfirmModel;
    InputModel: typeof DomainModels.InputModel;
    SpinnerModel: typeof DomainModels.SpinnerModel;
    TableModel: typeof DomainModels.TableModel;
    ToastModel: typeof DomainModels.ToastModel;
    SelectModel: typeof DomainModels.SelectModel;
    AutocompleteModel: typeof DomainModels.AutocompleteModel;
    TreeModel: typeof DomainModels.TreeModel;
    TabsModel: typeof DomainModels.TabsModel;
    AccordionModel: typeof DomainModels.AccordionModel;
    GalleryModel: typeof DomainModels.GalleryModel;
    PriceModel: typeof DomainModels.PriceModel;
    PricingModel: typeof DomainModels.PricingModel;
    CommentModel: typeof DomainModels.CommentModel;
    TestimonialModel: typeof DomainModels.TestimonialModel;
    StatsItemModel: typeof DomainModels.StatsItemModel;
    StatsModel: typeof DomainModels.StatsModel;
    TimelineItemModel: typeof DomainModels.TimelineItemModel;
    TimelineModel: typeof DomainModels.TimelineModel;
    HeaderVisibilityModel: typeof DomainModels.HeaderVisibilityModel;
    HeaderConfigModel: typeof DomainModels.HeaderConfigModel;
    FooterVisibilityModel: typeof DomainModels.FooterVisibilityModel;
    FooterConfigModel: typeof DomainModels.FooterConfigModel;
    EmptyStateModel: typeof DomainModels.EmptyStateModel;
    BannerModel: typeof DomainModels.BannerModel;
    ProfileDropdownModel: typeof DomainModels.ProfileDropdownModel;
    User: typeof User;
};
